#!/usr/bin/env bash
# This is a Bash (init) script 101-manage_my_process that manages manage_my_process.

SCRIPT="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

start() {
    if [ -e "$PID_FILE" ]; then
        echo "manage_my_process is already running."
    else
        $SCRIPT &
        echo $! > $PID_FILE
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -e "$PID_FILE" ]; then
        kill -9 $(cat $PID_FILE)
        rm -f $PID_FILE
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
